

# N mixture models: In General {#gen}


:::: {style="display: flex;"}

::: {.col data-latex="{0.45\textwidth}" style="font-style: italic; background-color: #ccccff; border-style:solid; width:45%"}

Pongamos que salimos al campo a buscar ciervos *(Cervus elaphus)*.

De forma general, se podría afirmar que si detectamos un individuo de ciervo durante el muestreo, la especie está presente en ese lugar y en ese momento (asumimos que conocemos bien la especie y que no hay posibilidad de obtener falsos positivos, esto es, confundir otras especies con individuos de ciervo, por ejemplo). Sin embargo, el hecho de no detectarla puede estar indicándonos dos cosas:

1. Que la especie **no esté presente** en ese lugar porque el hábitat no es el adecuado, o la especie se haya extinguido, etc. Esto sería un verdadero negativo.

2. Que la especie **si esté presente pero no hayamos sido capaces de detectarla** (hemos ido a muestrear al medio día y solo tiene actividad crepuscular, por ejemplo). Esto sería un falso negativo.

Los N-mixture models son capaces de tener en cuenta la posibilidad de cometer falsos negativos cuando muestreamos varias ocasiones los mismos sitios. Tienen en cuenta dos procesos:

- Un proceso (o submodelo) que determina la abundancia de la especie. En inglés suele denominarse state process.
- Un proceso (o submodelo) que determina la probabilidad de detección/observación de la especie. En inglés observational process.

Estos modelos suelen denominarse modelos jerárquicos ya que el proceso de detección depende en parte del proceso de abundancia. A continuación simularemos una serie de escenarios a modo de ejemplo para entender un poco mejor los N-mixture models.
:::

::: {.col data-latex="{0.05\textwidth}"}
\ 
<!-- an empty Div (with a white space), serving as
a column separator -->
:::

::: {.col data-latex="{0.45\textwidth}" style="width:45%"}

Let's say we go out into the field to look for deer *(Cervus elaphus)*.

In general, it could be stated that if we detect an individual deer during the sampling, the species is present in that place and at that time (we assume that we know the species well and that there is no possibility of obtaining false positives, that is, confusing other species with deer individuals, for example). However, the fact of not detecting it may be indicating two things:

1. That the species **is not present** in that place because the habitat is not adequate, or the species has become extinct, etc. This would be a real negative.

2. That the species **is present but we have not been able to detect it** (we have gone to sample at noon and it only has twilight activity, for example). This would be a false negative.

The N-mixture models are able to take into account the possibility of committing false negatives when we repeatedly sample the same sites. They take into account two processes:

- A process (or sub-model) that determines the abundance of the species. In English it is usually called the state process.
- A process (or sub-model) that determines the probability of detection / observation of the species. In English observational process.

These models are often called hierarchical models since the detection process depends in part on the abundance process. Below we will simulate a series of example scenarios to understand the N-mixture models a little better.

:::
::::

